# This is a basic CICD workflow for Mulesoft Projects
name: Build and Deploy from main branch
# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
env:
  MULE_KEY : ${{ secrets.MULE_KEY }}
  ENVIRONMENT_CLIENT_ID : ${{ secrets.ENVIRONMENT_CLIENT_ID }}
  ENVIRONMENT_CLIENT_SECRET : ${{ secrets.ENVIRONMENT_CLIENT_SECRET }}
  ANYPOINT_PLATFORM_CLIENT_ID : ${{ secrets.ANYPOINT_PLATFORM_CLIENT_ID }}
  ANYPOINT_PLATFORM_CLIENT_SECRET : ${{ secrets.ANYPOINT_PLATFORM_CLIENT_SECRET }}
  CONNECTED_APP : ${{vars.CONNECTED_APP }}
  ENVIRONMENT : ${{ vars.ENVIRONMENT }}
  PRIVATE_SPACE : ${{ vars.PRIVATE_SPACE }}
  BUSINESS_GROUP_ID : ${{ vars.BUSINESS_GROUP_ID }}
  BUSINESS_GROUP_NAME : ${{ vars.BUSINESS_GROUP_NAME }}
  MULE_ENV : ${{ vars.MULE_ENV }}
  BUILD_NUMBER : 1.0.1-${{ github.run_id }}${{ github.run_attempt }}-Dev
  WORKERS : ${{ vars.WORKERS }}
  VCORES : ${{ vars.VCORES }}
jobs:  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  #  environment: development
    steps:
      - uses: actions/checkout@v3
      - name: Cache Depenedencies
        uses: actions/setup-java@v2
        with:
            java-version: '17'
            distribution: 'adopt'
            cache: maven
      - name: check build number
        run: echo ${{ env.BUILD_NUMBER }}
      - name: Publish to Exchange
        run: mvn clean -B deploy -DskipMunitTests -Dgroup.id=${{ env.BUSINESS_GROUP_ID }} -Dversion.id=${{ env.BUILD_NUMBER }} --settings .maven/settings.xml
      - name: Deploy to Anypoint Runtime
        run: mvn clean -B deploy -DmuleDeploy -DskipMunitTests -Dgroup.id=${{ env.BUSINESS_GROUP_ID }} -Dversion.id=${{ env.BUILD_NUMBER }} --settings .maven/settings.xml
